//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace TurnstileWcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id { get; set; }
        public int VisitType { get; set; }
        public System.DateTime VisitDate { get; set; }
        public Nullable<int> Visitor_Id { get; set; }

        [IgnoreDataMember]
        public virtual Visitor Visitor { get; set; }
    }
}
